kind: Pod
apiVersion: v1
metadata:
  name: phpfpm-nginx
  label:
    app: php-pod
spec:
  volumes:
    - name: shared-files
      emptyDir: {}
    - name: nginx-config-volume
      configMap:
        name: nginx-config
  containers:
    - image: shayc12/my-php-app:1
      name: app
      volumeMounts:
        - name: shared-files
          mountPath: /var/www/html
      lifecycle:
        postStart:
          exec:
            command: ["/bin/sh", "-c", "cp -r /my_app/. /var/www/html"]
    - image: nginx:1.7.9
      name: nginx
      volumeMounts:
        - name: shared-files
          mountPath: /var/www/html
        - name: nginx-config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf