apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: html_app
  name: html_app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: html_app
  template:
    metadata:
      labels:
        app: html_app
    spec:
      containers:
      - image: shayc12/html_app:1
        name: html-app
        ports:
        - containerPort: 80
